In [1]:
import numpy as np


In [2]:
#array
oned_array = np.array([1, 2, 3])
print(oned_array)

[1 2 3]


In [3]:
rank1_vector = np.array([1, 2, 3, 4])
print(rank1_vector)

[1 2 3 4]


In [4]:
#ndim--find the dimension of the vector
print(rank1_vector.ndim)

1


In [5]:
#size--total number of item
print(rank1_vector.size)

4


In [6]:
print(rank1_vector.transpose())

[1 2 3 4]


In [7]:
row_vector = np.array([[1, 2, 3]])
print(row_vector)

[[1 2 3]]


In [8]:
print(row_vector.ndim)

2


In [9]:
print(row_vector.size)

3


In [10]:
print(row_vector.transpose())

[[1]
 [2]
 [3]]


In [11]:
print(row_vector)
print(row_vector.shape)

[[1 2 3]]
(1, 3)


In [12]:
print(row_vector[0])

[1 2 3]


In [13]:
#two dimensional array
twood_array = np.array([[1, 2, 3], [8, 9, 2]])
print(twood_array)

[[1 2 3]
 [8 9 2]]


In [16]:
print(twood_array[0])

[1 2 3]


In [17]:
print(twood_array[1])

[8 9 2]


In [18]:
print(twood_array[0][1])

2
